version: '2.2'
services:
  currencystock-postgresql:
    build: .
    image: currencystock-postgresql
    container_name: currencystock-postgresql
    ports:
      - 5430:5432
    networks:
      - currencystock
networks:
  currencystock:
